// mocks.js

app.controller('DummyCtrl', ['$scope', function ($scope) {
  $scope.dummy = {};
}]);

// bootstrapped stuff by Django does not exist in tests.
var baseLayers = [{"type": "TMS", "aggregation_type": "none", "min_zoom": 0, "min_zoom_click": null, "sublayers": [], "id": 1, "name": "Topografie", "url": "http://{s}.tiles.mapbox.com/v3/examples.map-szwdot65/{z}/{x}/{y}", "slug": "topography", "store_path": null, "temporal": false, "active": true, "order": 3, "z_index": 1, "baselayer": true, "overlayer": false}, {"type": "TMS", "aggregation_type": "none", "min_zoom": 0, "min_zoom_click": null, "sublayers": [], "id": 2, "name": "Satelliet", "url": "http://khms1.google.com/kh/v=145&x={x}&y={y}&z={z}&s=&token=66417", "slug": "satellite", "store_path": null, "temporal": false, "active": false, "order": 2, "z_index": 1, "baselayer": true, "overlayer": false}, {"type": "WMS", "aggregation_type": "none", "min_zoom": 0, "min_zoom_click": null, "sublayers": [], "id": 3, "name": "Hoogtekaart", "url": "http://raster.lizard.net/wms", "slug": "elevation", "store_path": "ahn2/wss", "temporal": false, "active": false, "order": 1, "z_index": 1, "baselayer": true, "overlayer": false}];
var layers = [{"type": "WMS", "aggregation_type": "none", "min_zoom": 0, "min_zoom_click": null, "sublayers": [], "id": 4, "name": "Landgebruik", "url": "http://raster.lizard.net/wms", "slug": "landuse", "store_path": "use/wss", "temporal": false, "active": false, "order": 1, "z_index": 15, "baselayer": false, "overlayer": true}, {"type": "ASSET", "aggregation_type": "none", "min_zoom": 8, "min_zoom_click": 8, "sublayers": [{"asset": "impervioussurface", "min_zoom": 15, "min_zoom_click": null}, {"asset": "pumpeddrainagearea", "min_zoom": 12, "min_zoom_click": null}, {"asset": "pipe", "min_zoom": 14, "min_zoom_click": 14}, {"asset": "manhole", "min_zoom": 17, "min_zoom_click": 17}, {"asset": "overflow", "min_zoom": 16, "min_zoom_click": 16}, {"asset": "outlet", "min_zoom": 16, "min_zoom_click": 16}, {"asset": "pumpstation_sewerage", "min_zoom": 13, "min_zoom_click": 13}, {"asset": "pressurepipe", "min_zoom": 14, "min_zoom_click": 14}, {"asset": "culvert", "min_zoom": 16, "min_zoom_click": 16}, {"asset": "weir", "min_zoom": 15, "min_zoom_click": 15}, {"asset": "bridge", "min_zoom": 14, "min_zoom_click": 14}, {"asset": "pumpstation_non_sewerage", "min_zoom": 8, "min_zoom_click": 8}, {"asset": "belt_channel", "min_zoom": 8, "min_zoom_click": null}, {"asset": "primary_channel", "min_zoom": 12, "min_zoom_click": null}, {"asset": "secundary_channel", "min_zoom": 13, "min_zoom_click": null}, {"asset": "channelsurface", "min_zoom": 14, "min_zoom_click": null}, {"asset": "channel", "min_zoom": 14, "min_zoom_click": null}, {"asset": "fixeddrainagelevelarea", "min_zoom": 10, "min_zoom_click": null}], "id": 5, "name": "Waterketen", "url": "http://staging.nxt.lizard.net/api/v1/tiles/{slug}/{z}/{x}/{y}.{ext}", "slug": "waterchain", "store_path": null, "temporal": false, "active": true, "order": 2, "z_index": 20, "baselayer": false, "overlayer": false}, {"type": "WMS", "aggregation_type": "none", "min_zoom": 0, "min_zoom_click": null, "sublayers": [], "id": 7, "name": "Regen", "url": "http://raster.lizard.net/wms", "slug": "demo:radar", "store_path": "radar/basic", "temporal": true, "active": false, "order": 3, "z_index": 25, "baselayer": false, "overlayer": false}];
var data_bounds = {"all": {"west": 3.04, "east": 7.58, "north": 53.63, "south": 50.57}};
var event_types = [{"event_series": 1, "type": "Overstorten", "event_count": 202}];