language: node_js
node_js: v11.0.0
cache: npm
install:
  - npm install -g bower
  - LIBSASS_EXT="no" npm install
  - bower install
# TODO: get grunt to work later on:
# - npm run dist
script:
  - npm test

# TODO: after-success "npm run transifex"
