language: node_js
node_js: v11.0.0
cache: npm
install:
  - npm install -g bower
  - LIBSASS_EXT="no" npm install
  - bower install
# TODO: get grunt to work later on:
# - npm run dist
# TODO get npm test to run on phantomjs browser
script:
#   - echo "npm test fails, but this is just for the test setup PR"
#   - npm test

# TODO: after-success "npm run transifex"
