language: node_js
install:
  - npm install -g bower
  - npm install
  - bower install
# TODO: get grunt to work later on:
# - npm run dist
script:
  - npm test

# TODO: after-success "npm run transifex"
