#!/usr/bin/env python

import getpass
import sys
import os

PROXY_HOST = 'https://nxt3.staging.lizard.net/'
CMD_TEMPLATE = ' npm start -- --proxyhost=%s --sso_username=%s --sso_password=%s'


def get_username():
    try:
        username = raw_input("[?] SSO username: ")
    except KeyboardInterrupt:
        print "\n[!] Aborting..."
        sys.exit(0)

    if username:
        print "[+] OK, we'll be using '%s' as username for this session." % \
            username
        return username
    else:
        print "[!] You have failed to enter a valid username. Please try again."
        return get_username()


def get_password():
    try:
        password = getpass.getpass('[?] SSO password: ')
    except KeyboardInterrupt:
        print "\n[!] Aborting..."
        sys.exit(0)

    if password:
        print "[+] OK, we'll be using %s as password." % (len(password) * '*')
        return password
    else:
        print "[!] You have failed to enter a valid password. Please try again."
        return get_password()


if __name__ == '__main__':
    username = get_username()
    password = get_password()
    os.system(
        CMD_TEMPLATE % \
        (PROXY_HOST, username, password)
    )
